# Build and run the application as default.
default: build run

# Build the application.
build:
	@g++ main1.cpp -o main1 -Wall -Werror

# Run the application.
run:
	@./main1

# Clean the application.
clean:
	@rm -f main1
