# Build and run the application as default.
default: build2 run2

# Build the first application (main1.cpp).
build1:
	@g++ main1.cpp -o main1 -Wall -Werror

# Run the first application.
run1:
	@./main1

# Build the second application (main2.cpp).
build2:
	@g++ main2.cpp -o main2 -Wall -Werror

# Run the second application.
run2:
	@./main2

# Clean both applications.
clean:
	@rm -f main1 main2
